# Generated by Django 4.2.9 on 2024-02-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_networkedge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkedge',
            unique_together={('from_user', 'to_user')},
        ),
    ]
