# Generated by Django 4.2.9 on 2024-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='caption_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
