# Generated by Django 4.2.9 on 2024-02-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_networkedge_unique_together'),
        ('contents', '0003_postlikes_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='users.userprofile'),
        ),
    ]
