# Generated by Django 4.2.9 on 2024-02-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_networkedge_unique_together'),
        ('contents', '0004_alter_postlikes_liked_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlikes',
            unique_together={('post', 'liked_by')},
        ),
    ]
